#!/bin/bash
set -euo pipefail

TIMESHIFTS_DIRECTORY_NAME=timeshifts
DOTGIT=$(git rev-parse --show-toplevel)/.git
TIMESHIFTS_DIRECTORY=$DOTGIT/$TIMESHIFTS_DIRECTORY_NAME

TIMESHIFT_TAR_FILENAME=timeshift.tar
STASH_FILENAME=stash

TIMESHIFT_HEAD_REF_NAME=TIMESHIFT_HEAD

: "mkdir .git/$TIMESHIFTS_DIRECTORY_NAME if it does not exist"
if [[ ! -e $TIMESHIFTS_DIRECTORY ]]; then
    mkdir -p $TIMESHIFTS_DIRECTORY
fi

: "check if .git/$TIMESHIFTS_DIRECTORY_NAME is a directory"
if [[ ! -d $TIMESHIFTS_DIRECTORY ]]; then
    echo "'.git/$TIMESHIFTS_DIRECTORY_NAME' is not a directory" 1>&2
    exit 1
fi

: "show timeshifts"
ls -r $TIMESHIFTS_DIRECTORY | awk '{print "["NR"]:"$1}' | sed 's/^\(.*\)\.tar\.gz$/\1/'
