#!/bin/bash
set -xeuo pipefail

TIMESHIFTS_DIRECTORY_NAME=timeshifts
DOTGIT=$(git rev-parse --show-toplevel)/.git
TIMESHIFTS_DIRECTORY=$DOTGIT/$TIMESHIFTS_DIRECTORY_NAME

TIMESHIFT_TAR_FILENAME=timeshift.tar
STASH_FILENAME=stash

TIMESHIFT_HEAD_REF_NAME=TIMESHIFT_HEAD

EMPTY_TREE=4b825dc642cb6eb9a060e54bf8d69288fbee4904


: "mkdir .git/$TIMESHIFTS_DIRECTORY_NAME if it does not exist"
if [[ ! -e $TIMESHIFTS_DIRECTORY ]]; then
  mkdir -p $TIMESHIFTS_DIRECTORY
fi

: "check if .git/$TIMESHIFTS_DIRECTORY_NAME is a directory"
if [[ ! -d $TIMESHIFTS_DIRECTORY ]]; then
  echo "'.git/$TIMESHIFTS_DIRECTORY_NAME' is not a directory" 1>&2
  exit 1
fi

: "backup the current git state to the timeshift file"
COMMIT_HASH=$(git rev-parse HEAD)
STASH_HASH=""
if git stash -u | grep -q 'Saved working directory'; then
  COMMIT_HASH=$(git rev-parse stash)
  STASH_HASH=$COMMIT_HASH
  git stash pop --index >/dev/null
fi

cd $DOTGIT

: "create timeshift tar object"
TIMESHIFT_TAR_OBJECT_HASH=$(tar cf - --exclude ./$TIMESHIFT_HEAD_REF_NAME --exclude ./$TIMESHIFTS_DIRECTORY_NAME --exclude ./objects . | git hash-object -w --stdin)

: "create stash object"
STASH_OBJECT_HASH=""
if [[ -n "$STASH_HASH" ]]; then
  STASH_OBJECT_HASH=$(git hash-object -w --stdin <<< "$STASH_HASH")
fi

: "create timeshift tree"
ORIGINAL_TREE=$(git write-tree)
git read-tree $EMPTY_TREE
trap "git read-tree $ORIGINAL_TREE" EXIT
git update-index --add --cacheinfo 100644 $TIMESHIFT_TAR_OBJECT_HASH $TIMESHIFT_TAR_FILENAME
if [[ -n "$STASH_OBJECT_HASH" ]]; then
  git update-index --add --cacheinfo 100644 $STASH_OBJECT_HASH $STASH_FILENAME
fi
TIMESHIFT_TREE_HASH=$(git write-tree)

: "create timeshift commit"
PARENTS_OPTIONS="-p $COMMIT_HASH $(git for-each-ref --shell --format '-p %(refname)' refs/heads | xargs)"
TIMESHIFT_COMMIT_HASH=$(git commit-tree $TIMESHIFT_TREE_HASH $PARENTS_OPTIONS -m "Timeshift")

echo $TIMESHIFT_COMMIT_HASH >$TIMESHIFTS_DIRECTORY/$TIMESHIFT_COMMIT_HASH
git update-ref $TIMESHIFT_HEAD_REF_NAME $TIMESHIFT_COMMIT_HASH

echo "Timeshift saved to $TIMESHIFT_COMMIT_HASH"
